import { TicketType } from 'src/app/types/ticket.type';

export const ticketsData: TicketType[] = [
  {
    id: 1,
    user: {
      name: 'محمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 2,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
      image: '../../../../assets/images/person.png',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 50,
  },
  {
    id: 3,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
      image: '../../../../assets/images/person.png',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان', 'سرايا القبة'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 4,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
      image: '../../../../assets/images/person.png',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 5,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 6,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 7,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 8,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 9,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 10,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 11,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
  {
    id: 12,
    user: {
      name: 'أحمد محمود',
      phone: '0123456789',
    },
    cinemas: ['سينما مصر', ' مول العرب', 'برج الأطنان'],
    numberOfPeople: 1,
    numberOfPurchases: 'مرة واحدة',
    ticketFile: {
      fileName: 'تذكرة رقم 45.pdf',
      fileSize: '9mb',
      fileType: 'pdf',
    },
    ticketNumber: 101,
    ticketPrice: 40,
  },
];
